// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'banner': string;
  'bannerGrow': string;
  'certification': string;
  'gameType': string;
  'genres': string;
  'latestPlatform': string;
  'monitorNewItems': string;
  'network': string;
  'nextAiring': string;
  'originalCountry': string;
  'originalLanguage': string;
  'path': string;
  'platformCount': string;
  'platformFolder': string;
  'previousAiring': string;
  'qualityProfileId': string;
  'ratings': string;
  'releaseGroups': string;
  'romCount': string;
  'romProgress': string;
  'sizeOnDisk': string;
  'sortTitle': string;
  'status': string;
  'tags': string;
  'useSceneNumbering': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
