// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'extensions': string;
  'folder': string;
  'gameSystem': string;
  'name': string;
  'naming': string;
  'namingLabel': string;
  'type': string;
}
export const cssExports: CssExports;
export default cssExports;
