// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteRomNumber': string;
  'airTime': string;
  'downloaded': string;
  'downloading': string;
  'event': string;
  'gameTitle': string;
  'info': string;
  'missing': string;
  'onAir': string;
  'overlay': string;
  'romInfo': string;
  'romTitle': string;
  'statusContainer': string;
  'statusIcon': string;
  'unaired': string;
  'underlay': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
