// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteRomNumber': string;
  'airTime': string;
  'airingInfo': string;
  'collapseContainer': string;
  'downloaded': string;
  'downloading': string;
  'eventGroup': string;
  'expandContainer': string;
  'expandContainerInline': string;
  'gameTitle': string;
  'info': string;
  'missing': string;
  'onAir': string;
  'premiere': string;
  'romInfo': string;
  'statusContainer': string;
  'statusIcon': string;
  'unaired': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
