// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'event': string;
  'gameTitle': string;
  'info': string;
  'overlay': string;
  'platformCount': string;
  'source': string;
  'underlay': string;
}
export const cssExports: CssExports;
export default cssExports;
