// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'checkboxCell': string;
  'fileDetails': string;
  'filesCell': string;
  'footer': string;
  'footerLeft': string;
  'header': string;
  'headerCell': string;
  'importingSpinner': string;
  'nameCell': string;
  'pathInput': string;
  'resultError': string;
  'resultSuccess': string;
  'resultsSection': string;
  'row': string;
  'scanSection': string;
  'selectedCount': string;
  'sizeCell': string;
  'systemBadge': string;
  'systemCell': string;
  'table': string;
  'typeCell': string;
}
export const cssExports: CssExports;
export default cssExports;
