// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteRomNumber': string;
  'date': string;
  'downloaded': string;
  'downloading': string;
  'episodeSeparator': string;
  'event': string;
  'eventWrapper': string;
  'gameTitle': string;
  'missing': string;
  'onAir': string;
  'overlay': string;
  'premiere': string;
  'romTitle': string;
  'seasonRomNumber': string;
  'statusIcon': string;
  'time': string;
  'unaired': string;
  'underlay': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
