// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'event': string;
  'eventWrapper': string;
  'gameTitle': string;
  'overlay': string;
  'platformCount': string;
  'source': string;
}
export const cssExports: CssExports;
export default cssExports;
